# -*- coding: utf-8 -*-
"""Fillinvalues.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0gB096gTCGiQrv9dZQACiKKD0LPCWoD
"""

import pandas as pd

# dependent variables path
dep_path = 'https://raw.githubusercontent.com/Mreavisjr/proj-j2022/main/data/dependent_variables.csv'

# independent variables path
ind_path = 'https://raw.githubusercontent.com/Mreavisjr/proj-j2022/main/data/independent_variables.csv'

# dependents as dataframe
dependents = pd.read_csv(dep_path)

# independents as dataframe
independents = pd.read_csv(ind_path)

# merge both into single dataframe
house_data = pd.merge(dependents, independents).drop('Unnamed: 0', axis= 1)

# create column for whether value was missing or not
house_data['income_was_missing'] = house_data['median-income'].isnull()

# change column names to snake case in order to work better with linear regression model
house_columns = []
house_data.columns
for col in house_data.columns:
  new = col.replace('-', '_')
  house_columns.append(new)

# apply new column names
house_data.columns = house_columns

# create copy to make it easier to change how we fill missing values if decide to use different method
house_copy = house_data.copy()

# fill missing values with median of all values in column
house_copy['median_income'] = house_copy['median_income'].fillna(house_copy['median_income'].median())

# import linear regression model
from statsmodels.formula.api import ols

# first test model using new median values
model1 = ols("closed_sales ~ average_price + months_supply + median_income", data= house_copy).fit()
print(model1.summary())

# second model that takes into account if the value was filled in or not
model2 = ols("closed_sales ~ average_price + months_supply + median_income + C(income_was_missing)", data= house_copy).fit()
print(model2.summary())

# second model has a very slightly improved r-squared score